/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Applications;

/**
 *
 * @author Jeevesh
 */
public class ChoiceCalculator extends javax.swing.JFrame {

    /**
     * Creates new form ChoiceCalculator
     */
    public ChoiceCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fn_lbl = new javax.swing.JLabel();
        fn_txt = new javax.swing.JTextField();
        sn_lbl = new javax.swing.JLabel();
        sn_txt = new javax.swing.JTextField();
        sum_rd = new javax.swing.JRadioButton();
        mul_rd = new javax.swing.JRadioButton();
        rs_lbl = new javax.swing.JLabel();
        cb_agree = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fn_lbl.setText("First Number");

        fn_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fn_txtActionPerformed(evt);
            }
        });

        sn_lbl.setText("Second Number");

        buttonGroup1.add(sum_rd);
        sum_rd.setText("Sum");
        sum_rd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sum_rdItemStateChanged(evt);
            }
        });

        buttonGroup1.add(mul_rd);
        mul_rd.setText("Multiplication");
        mul_rd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mul_rdActionPerformed(evt);
            }
        });

        cb_agree.setText("I Agree");
        cb_agree.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_agreeItemStateChanged(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cb_agree)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(21, 21, 21)
                                .addComponent(jButton2))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sn_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(fn_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rs_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sum_rd)
                                .addGap(18, 18, 18)
                                .addComponent(mul_rd))
                            .addComponent(fn_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(sn_txt))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fn_lbl)
                    .addComponent(fn_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sn_lbl)
                    .addComponent(sn_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sum_rd)
                    .addComponent(mul_rd))
                .addGap(18, 18, 18)
                .addComponent(cb_agree)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rs_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mul_rdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mul_rdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mul_rdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int fn = Integer.parseInt(fn_txt.getText());
        int sn = Integer.parseInt(sn_txt.getText());
        if(sum_rd.isSelected())
        {
             rs_lbl.setText(String.valueOf(fn+sn));
        }
        if(mul_rd.isSelected())
        {
             rs_lbl.setText(String.valueOf(fn*sn));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sum_rdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sum_rdItemStateChanged
        // TODO add your handling code here:
//           int fn = Integer.parseInt(fn_txt.getText());
//        int sn = Integer.parseInt(sn_txt.getText());
//        rs_lbl.setText(String.valueOf(fn+sn));
    }//GEN-LAST:event_sum_rdItemStateChanged

    private void fn_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fn_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fn_txtActionPerformed

    private void cb_agreeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_agreeItemStateChanged
        // TODO add your handling code here:
        if(cb_agree.isSelected())
        {
            jButton1.setEnabled(true);
        }
        else
        {
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_cb_agreeItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fn_txt.setText("");
        sn_txt.setText("");
        rs_lbl.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoiceCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoiceCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoiceCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoiceCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ChoiceCalculator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cb_agree;
    private javax.swing.JLabel fn_lbl;
    private javax.swing.JTextField fn_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JRadioButton mul_rd;
    private javax.swing.JLabel rs_lbl;
    private javax.swing.JLabel sn_lbl;
    private javax.swing.JTextField sn_txt;
    private javax.swing.JRadioButton sum_rd;
    // End of variables declaration//GEN-END:variables
}
